### PR TITLE
Newsweek clone implementation

### PR DESCRIPTION
**Pull request by marcoshdezcam**
This project is a replica of the Newsweek website using Bootstrap. SASS was used to customize it and export everything to a single CSS file including all styles. 
[Original](https://www.newsweek.com/)
[Live Demo](https://marcoshdezcam.github.io/gh-pages-lives/P7_Newsweek_Bootstrap)

- SASS for customizing Bootstrap
- Bootstrap framework & customizations compiled in 1 single CSS file to reduce HTTP requests.
- To modularize the SASS code the styles were separated in different files using mixins

*Changed stickler.yml file to include new rule at-rule-no-unknown to enable the possibility of using mixins as a feature of SASS.

### CODE REVIEW

**Comment by santiago-dev96** [comment]
# Pull Request under review by @santiago-rodrig (TSE)

**Review by santiago-dev96 — CHANGES_REQUESTED** [review]
# Changes required :no_entry_sign:
You still have some linter errors, if you can justify it, you can edit the `.stickler.yml` configuration file. The next reviewer will see your comment in the configuration file (because your justification should be present in the configuration file itself too) and then go on with the review process. I also noticed that your PR title and summary are not professional at all, they should be something like the following.

> ### Newsweek cloning implementation
> - major change 1
> - major change 2
> ...
> Some conclusions and details to note.

Please submit another CRR (Code Review Request) after implementing the required changes.

You can find me in slack as **srodrig**. Have a nice day :wave:!

**Comment by marcoshdezcam** [comment]
Thank you for your comments, really appreciated. 
Suggestions applied to the project and CRR made.

**Review by sumancrest0001 — COMMENTED** [review]
**Status: changes required**
Very impressive work @marcoshdezcam. Nicely managed file structure. Everything looks perfect to me on the large screen but on the medium and small screen, we need to fix a couple of issues.
[NOTE] All the changes are mandatory.
on the medium screen, the signup sections shouldn't cover the whole screen. In fact, it should be centered. have a look :point_down: 
Screenshot from 2020-05-18 08-00-54
It should be like this :point_down: 
Screenshot from 2020-05-18 08-00-33

On the small screen, the newsletter section should be one column but currently, it's two-column. Following images make it more clear.
in your project :point_down: 
Screenshot from 2020-05-18 08-02-28

In the original project :point_down: 
Screenshot from 2020-05-18 08-02-42

**Review by sumancrest0001 — CHANGES_REQUESTED** [review]
Kindly make the requested changes and submit another review request. 

If you have any question regarding review, please reach out to me on slack (**Suman Shrestha**)
**Happy coding !!!**

**Comment by marcoshdezcam** [comment]
Comments really appreciated and changes applied.

**Review by lucasmazo32 — APPROVED** [review]
# Project approved :rocket:

#### Great job!

#### Your project looks great!

- [OPTIONAL] For some reason your page is not displaying the footer on Firefox, if you want to take a look at it, it would be great.

### You can go ahead and merge this pull request!

### Happy coding! :computer:

## Lucas Mazo

**Comment by marcoshdezcam** [comment]
Thanks for the comments.

**Pull request merged**
